#Dockerfile docker-grav
FROM ubuntu
LABEL tlnk <support@tlnk.fr>

ARG VERSION
ARG BUILD_DATE
ARG VCS_REF

EXPOSE 80

#Install packages
RUN apt-get update -y && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ondrej/php && \
    apt-get update -y && \
    apt-get upgrade -y

RUN apt-get install -y tzdata && \
   ln -fs /usr/share/zoneinfo/UTC /etc/localtime
RUN apt-get install -y nano \
    zip \
    unzip \
    nginx \
    git \
    php7.0-fpm \
    php7.0-cli \
    php7.0-gd \
    php7.0-curl \
    php7.0-mbstring \
    php7.0-xml \
    php7.0-zip \
    php-apcu

COPY entrypoint /entrypoint
COPY grav.conf /etc/nginx/sites-available/grav.conf

RUN mkdir /var/www/grav && \
    git clone https://github.com/getgrav/grav.git /var/www/grav && \
    ln -s /etc/nginx/sites-available/grav.conf   /etc/nginx/sites-enabled/grav.conf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /etc/nginx/sites-enabled/default && \
    rm -rf /var/www/html && \
    chmod +x /entrypoint/*sh && \
    chmod +x /entrypoint/entrypoint.d/*.sh

RUN nginx -t
RUN /var/www/grav/bin/grav install

WORKDIR /var/www/grav

ENTRYPOINT ["/bin/bash", "/entrypoint/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]


LABEL org.label-schema.version=$VERSION
LABEL org.label-schema.build-date=$BUILD_DATE
LABEL org.label-schema.vcs-ref=$VCS_REF
LABEL org.label-schema.vcs-url="https://github.com/tle06/docker-grav.git"
LABEL org.label-schema.name="docker-grav"
LABEL org.label-schema.vendor="docker-grav"
LABEL org.label-schema.schema-version="1.0"